#!/usr/bin/env bash

# This script was generated by ChatGPT (2025-04-26).
# It creates a changelog file with a bump type and user-provided notes.

set -e  # Exit immediately if a command exits with a non-zero status

# Find the root of the git repository
git_root=$(git rev-parse --show-toplevel 2>/dev/null || true)

if [ -z "$git_root" ]; then
  echo "Error: Not inside a git repository."
  exit 1
fi

# Default target directory
target_dir="$git_root/dagger/changelogs"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dir)
      target_dir="$2"
      shift 2
      ;;
    major|minor|patch)
      bumptype="$1"
      shift
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

# Create timestamp
timestamp=$(date +"%Y%m%d-%H%M%S")

# Create a temporary file
tmpfile=$(mktemp /tmp/changelog-note.XXXXXX.md)

# Clean up temp file on exit
trap 'rm -f "$tmpfile"' EXIT

# Write initial content to the temp file
cat <<EOF > "$tmpfile"
EOF

# Open the temp file with the default editor
${EDITOR:-vi} "$tmpfile"

# If bump-type wasn't provided, ask the user
if [ -z "$bumptype" ]; then
  read -p "Enter bump type (major/minor/patch): " bumptype
fi

# Validate bump-type
if [[ "$bumptype" != "major" && "$bumptype" != "minor" && "$bumptype" != "patch" ]]; then
  echo "Error: bump type must be one of: major, minor, patch."
  exit 1
fi

# Create the target directory if it doesn't exist
mkdir -p "$target_dir"

# Build the target filename
filename="$target_dir/changelog-$timestamp.md"

# Write the final file (all lines, including comments, will be written)
{
  echo "---"
  echo "bump-type: $bumptype"
  echo "---"
  echo
  cat "$tmpfile"
} > "$filename"

echo "changelog file created: $filename"
